# 测试后端api接口

@hostname = chatdao.com
@port = 3031

@host = {{hostname}}:{{port}}
@hostpro = www.justdao.com/api/v1
@contentType = application/json

@testemail = 27681135@qq.com
@createdAt = {{$datetime iso8601}}
@token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2MDI4MzY0MDYsImlkIjoxMDAwOX0.E7rsmZiWmrpOkmnnis384RX4dREZsx8ZblR_-pkzvc4
@tokenpro=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2MDQ4ODYwNjQsImlkIjoxMDAwM30.o2s29FZN7ile0BWUZ3SseWOgQFR61qhuCHET9mqOCJo
@testUserId = 10009
# token半年有效

# 币价接口
@tokenapikey=64e6c84a-b974-4572-83a7-e9e1f81264a5

### 测试货币接口
GET https://pro-api.coinmarketcap.com/v1/fiat/map
X-CMC_PRO_API_KEY: {{tokenapikey}}

### 获取币种
GET https://pro-api.coinmarketcap.com/v1/cryptocurrency/map
X-CMC_PRO_API_KEY: {{tokenapikey}}

### 币种行情
GET https://pro-api.coinmarketcap.com/v1/cryptocurrency/quotes/latest?id=1027
X-CMC_PRO_API_KEY: {{tokenapikey}}


### 未登录推荐组
GET {{host}}/grp/recommend 


### GET /user/verify/:mail（发送验证码）
GET https://{{host}}/user/verify/{{testemail}}
### POST /user/login（登陆）
POST https://{{host}}/user/login HTTP/1.1

{
	"mail": "{{testemail}}",
	"code": "4897"
}

### GET /grp/:id （群信息）
### GET /user/members/:grp_id（群成员）
### GET /comments/:post_id（获取评论）
### GET /user/:id（用户信息）
GET https://{{host}}/user/{{testUserId}} HTTP/1.1

### GET /protected/user/me（自己信息）
GET https://{{host}}/protected/user/me HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: {{contentType}}
### POST /protected/grp/create（创建群）
{
	"name": "w",
	"desc_text": "f",
	"password": "g",
	"read_permission": 1,
        "avatar": ""
}
### GET /protected/grp/joined（已加入的群）
### GET /grp/recommend (未登陆) || GET /protected/grp/recommend (已登陆) （群推荐）
GET https://{{host}}/protected/grp/recommend HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: {{contentType}}


### POST /protected/grp/join（加群）
POST https://{{host}}/protected/grp/join HTTP/1.1

Authorization: Bearer {{token}}
Content-Type: {{contentType}}

{
  "grp": 1,
  "password": ""
}
### POST /protected/grp/detach（退群）
POST https://{{host}}/protected/grp/detach HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: {{contentType}}

{
  "grp": 10015
}

### POST /protected/post/create（发帖）
POST https://{{host}}/protected/post/create HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: {{contentType}}

{
	"grp": 10018,
	"title": "文本plain text",
	"content": "内容可以放入html",
  "images": [
    "aws s3 url",
    "aws s3 url"
  ]
}
### POST /protected/post/like（点赞）
{
	"post": 1,
	"op": 2
}
### POST /protected/post/likes（点赞状态）
{
	"posts": [1, 2]
}
### POST /protected/comment/create（评论）
{
	"post": 1,
	"content": "comment content here",
	"ref_comment": null
}
### POST /protected/post/pull (已登陆) || POST /post/pull (未登陆) （获取帖子）
{
	"grp": 2,
	"base_post": null
}
### POST /protected/post/my/pull（我发布的帖子）
{
    "base_post": null,
    "deleted": false
}
### DELETE /protected/post（删帖）
DELETE  https://{{host}}/protected/post HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: {{contentType}}

{
    "post": 32
}

### PUT /protected/post（更新帖子）
{
    "id": 1,
    "title": "hh",
    "content": "uu",
    "images": []
}
### PUT /protected/user/modify（修改个人信息）
PUT  https://{{host}}/protected/user/modify HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: {{contentType}}

{
	"name": "杨旭",
  "avatar": "https://s3.ap-northeast-1.amazonaws.com/justdao/dev/10009/op.jpg"
}
### GET /protected/user/tokens（我的代币）
GET https://{{hostpro}}/protected/user/tokens HTTP/1.1
Authorization: Bearer {{tokenpro}}

### POST /protected/user/token/transfer（转账）
POST  https://{{host}}/user/token/transfer HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: {{contentType}}

{
    "contract": "",
    "to_user": 10007,
    "value": "0"
}
### POST /protected/user/token/logs（转账日志）
{
    "contract": "",
    "base_token_log": null
}
### GET /protected/user/notifications/:base_notification（获取通知）
# 注：read 字段参见枚举定义, base_notification 参数为之前保存的最新通知id，首次获取置0
GET https://{{host}}/protected/user/notifications/0 HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: {{contentType}}
### POST /protected/grp/block（拉黑）
{
  "grp": 1,
  "user": 2,
  "block": 2
}
### POST /grp/against（搜索群）
{
	"kw": "王者"
}
### POST /protected/grp/pin（置顶群）
POST https://{{host}}/protected/grp/pin HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: {{contentType}}

{
  "grp": 10018,
  "pinned": 2
}

### POST /protected/oss/presign
POST https://{{host}}/protected/oss/presign HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: {{contentType}}

{
  "key": "my-avatar.jpg"
}

### POST /protected/moon/categories（置顶群）
POST https://{{host}}/protected/moon/categories HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: {{contentType}}

{
  "grp": 10018,
  "categories": [42]
}

# s3上传预签名
# 注意：前端拿到 headers 和 presigned_url 后向s3上传对象，其中 headers 是字典，需遍历添加到往s3的请求header内，body必须是纯 binary 数据，非 form-data，参见 
# https://github.com/aws/aws-sdk-js/issues/547#issuecomment-86404872
# https://github.com/rowanwins/vue-dropzone/issues/411#issuecomment-459255756
# 往s3的报文格式
# PUT <data.presigned_url>
# <common-headers>
# <data.headers>
# <binary data>
# 上传成功后，presigned_url 去除query string后的部分作为资源路径，用于其他接口使用，如更新个人信息
# https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/s3-example-photo-album.html